#!/bin/sh

## Helpers

command_exists() { command -v "$1" >/dev/null; }

## Common commands

if command_exists exa; then
  # https://the.exa.website/docs/colour-themes
  alias _ls='EXA_COLORS="da=1;34" exa --group-directories-first --classify'
  alias l='_ls'
  alias ll='_ls --long'
  alias la='_ls --long --all'
  alias lt='_ls --long --time modified'
  alias lr='_ls --recurse'
  alias ldot='_ls --long --list-dirs .*'
  alias tree='_ls --tree'
else
  alias _ls='ls -Fh'
  alias l='_ls'
  alias ll='_ls -l'
  alias la='_ls -lA'
  alias lt='_ls -lt'
  alias lr='_ls -R'
  alias ldot='_ls -ld .*'
fi

alias cd..='cd ../'
alias ..='cd ../'
alias ~="cd ~"

alias cp='cp -iv'
alias grep='grep --color=always'
alias mv='mv -iv'
alias path='echo -e ${PATH//:/\\n}'
alias rm='rm -vI'
trash () { command mv "$@" ~/.Trash ; }

## Git

alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gba='git branch --all'
alias gc='git commit --verbose'
alias gc!='git commit --verbose --amend'
alias gcn!='git commit --verbose --no-edit --amend'
alias gc0='git commit --allow-empty -m "empty commit"'
alias gco='git checkout'
alias gd='git diff'
alias gdca='git diff --cached'
alias gf='git fetch'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias gp='git push'
alias gpf='git push --force-with-lease --force-if-includes'
alias gpf!='git push --force'

## Elixir

# https://hexdocs.pm/hex/Mix.Tasks.Hex.Docs.html
alias hexdocs='mix hex.docs online'

## Ruby

alias be='bundle exec'

## Others

alias timestamp='date "+%Y%m%d%H%M%S"'
alias 2desk='tee ${HOME}/Desktop/terminal-output-$(timestamp).txt'

# Run a simple web server
command_exists npx && alias serve='npx serve'
