#!/bin/bash

## Common commands

if command -v eza &>/dev/null; then
  # https://github.com/eza-community/eza
  alias ls='eza --group-directories-first --classify'
  alias ll='ls --long'
  alias la='ls --long --all'
  alias lt='ls --long --time modified'
  alias lr='ls --recurse'
  alias l.='ls --long --list-dirs .*'
fi

alias ..='cd ../'
alias ...='cd ../../'
alias cp='cp -iv'
alias grep='grep --color=always'
alias mv='mv -iv'
alias path='echo -e ${PATH//:/\\n}'
alias rm='rm -vI'
alias rmd='rm -rf'
trash() { mv "$@" ~/.Trash; }
alias wget='wget -c'

alias dud='du -d 1 -h' # Short and human-readable directory listing
alias duf='du -sh *'   # Short and human-readable file listing

alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'

alias count_files="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"

# Searches for text in all files in the current folder
find_text() { grep -iIHrn --color=always "$1" . | less -r; }

## Chmod

# https://github.com/ohmybash/oh-my-bash/blob/d025bddc67ace7e44dc894ca96a12887249dad06/aliases/chmod.aliases.sh
alias 000='chmod 000' # ---------- (nobody)
alias 640='chmod 640' # -rw-r----- (user: rw, group: r)
alias 644='chmod 644' # -rw-r--r-- (user: rw, group: r, other: r)
alias 755='chmod 755' # -rwxr-xr-x (user: rwx, group: rx, other: rx)
alias 775='chmod 775' # -rwxrwxr-x (user: rwx, group: rwx, other: rx)

## Archives

alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

## Git

alias ga='   git add'
alias gaa='  git add --all'
alias gb='   git branch'
alias gba='  git branch --all'
alias gc='   git commit --verbose'
alias gc!='  git commit --verbose --amend'
alias gcn!=' git commit --verbose --no-edit --amend'
alias gc0='  git commit --allow-empty -m "empty commit"'
alias gco='  git checkout'
alias gd='   git diff'
alias gdca=' git diff --cached'
alias gf='   git fetch'
alias glog=' git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias gp='   git push'
alias gpf='  git push --force-with-lease --force-if-includes'
alias gpf!=' git push --force'

## Elixir

# https://hexdocs.pm/hex/Mix.Tasks.Hex.Docs.html
alias hexdocs='mix hex.docs online'

## Ruby

alias be='bundle exec'

## Others

alias timestamp='date "+%Y%m%d%H%M%S"'
alias 2desk='tee ${HOME}/Desktop/terminal-output-$(timestamp).txt'

# Run a simple web server
command -v npx &>/dev/null && alias serve='npx serve'
