#!/bin/bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Cross-Desktop Group (XDG) directories
# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

if [ "$(uname)" = "Darwin" ]; then
  export XDG_RUNTIME_DIR="$HOME/Library/Caches/TemporaryItems"
else
  export XDG_RUNTIME_DIR="/run/user/$UID"
fi
mkdir -p "$XDG_RUNTIME_DIR"

## Helpers

command_exists() { command -v "$1" >/dev/null; }

## Variables

source "$XDG_CONFIG_HOME/shell/variables"

# Bash-specific variables
export HISTCONTROL=erasedups:ignoredups:ignorespace
export HISTFILE="$HOME/.bash_history"
export HISTIGNORE="history:ls:pwd:cd:"
export HISTFILESIZE=10000
export HISTSIZE=${HISTFILESIZE}
shopt -s histappend

# ensure synchronization between bash memory and history file
export PROMPT_COMMAND="history -a; history -n"

## Git completion

# https://git-scm.com/book/en/v2/Appendix-A:-Git-in-Other-Environments-Git-in-Bash
mkdir -p "$XDG_CONFIG_HOME/git"
git_completion_script="$XDG_CONFIG_HOME/git/git-completion.bash"

if [ ! -f "$git_completion_script" ]; then
  curl -L https://raw.github.com/git/git/master/contrib/completion/git-completion.bash >"$git_completion_script"
fi

source "$git_completion_script"

## zoxide

# https://github.com/ajeetdsouza/zoxide
if ! command_exists zoxide; then
  curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
fi

eval "$(zoxide init bash)"

## Bash Line Editor (ble.sh)

ble_source_dir="$XDG_CONFIG_HOME/blesh"
ble_install_dir="$XDG_DATA_HOME/blesh"

if [ ! -d "$ble_source_dir" ]; then
  git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git "$ble_source_dir"
  # install to $XDG_DATA_HOME/blesh
  make --directory "$ble_source_dir" install
fi

if [[ $- == *i* ]] && [[ -z "${BLE_VERSION-}" ]]; then
  # https://github.com/akinomyoga/ble.sh
  source "$ble_install_dir/ble.sh" --noattach

  # https://github.com/akinomyoga/ble.sh/wiki
  bleopt complete_limit=100
  bleopt complete_timeout_auto=1000
  bleopt edit_abell=
fi

## HSTR configuration

# https://github.com/dvorka/hstr
if [[ $- =~ .*i.* ]] && command_exists hstr; then
  export HSTR_CONFIG=hicolor # get more colors
  export HSTR_TIOCSTI=y

  bind '"\C-r": "\C-a hstr -- \C-j"'
  bind '"\C-xk": "\C-a hstr -k \C-j"'
fi

## asdf

ASDF_DIR="${ASDF_DIR:-$HOME/.asdf}"

# https://asdf-vm.com/guide/getting-started.html
if [ -f "$ASDF_DIR/asdf.sh" ]; then
  source "$ASDF_DIR/asdf.sh"

  if [ -f "$ASDF_DIR/completions/asdf.bash" ]; then
    source "$ASDF_DIR/completions/asdf.bash"
  fi
fi

## direnv

# https://direnv.net/docs/hook.html
command_exists direnv && eval "$(direnv hook bash)"

## Shell prompt

# https://starship.rs
if ! command_exists starship; then
  curl -sS https://starship.rs/install.sh | sh
fi

eval "$(starship init bash)"

### Common shell stuff

source "$XDG_CONFIG_HOME/shell/aliases"
source "$XDG_CONFIG_HOME/shell/editors"
source "$XDG_CONFIG_HOME/shell/functions"

## Wrapping up

# Clean up PATH
PATH=$(printf "%s" "$PATH" | awk -v RS=':' '!a[$1]++ { if (NR > 1) printf RS; printf $1 }')

# Do this at the very end so that we can tell all above is executed
pcall neofetch

# Do this line at the end of .bashrc:
# https://github.com/akinomyoga/ble.sh
[[ ${BLE_VERSION-} ]] && ble-attach
