#!/bin/bash

command_exists() { command -v "$1" &>/dev/null; }

[ -z "$EDITOR" ] && command_exists nvim && EDITOR="nvim"
[ -z "$EDITOR" ] && command_exists vim && EDITOR="vim"

# https://hexdocs.pm/iex/IEx.Helpers.html#open/1
[ -z "$ELIXIR_EDITOR" ] && command_exists codium && ELIXIR_EDITOR="codium --goto"
[ -z "$ELIXIR_EDITOR" ] && command_exists code && ELIXIR_EDITOR="code --goto"

export EDITOR="$EDITOR"
export VISUAL="$EDITOR"
export ELIXIR_EDITOR="$ELIXIR_EDITOR"

# for project directories, cd first so that grepping works
alias dot=' cd ${DOTFILES_DIR} && ${EDITOR} .       ;'
alias memo='cd ${VIMWIKI_DIR}  && ${EDITOR} index.md;'
