#!/bin/bash

## Cross-Desktop Group (XDG) directories

# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
mkdir -p "$XDG_CACHE_HOME"
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_STATE_HOME"

if [ "$(uname)" = "Darwin" ]; then
  export XDG_RUNTIME_DIR="$HOME/Library/Caches/TemporaryItems"
else
  export XDG_RUNTIME_DIR="/run/user/$UID"
fi
mkdir -p "$XDG_RUNTIME_DIR"

## User-defined

export VIMWIKI_DIR="$HOME/Documents/vimwiki"

## Editors

export EDITOR="${EDITOR:-nvim}"
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
export ELIXIR_EDITOR="${ELIXIR_EDITOR:-$EDITOR}"

## Manual pages

export MANPAGER="less -R --use-color --color=d+r --color=u+y"

## X11

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

## Homebrew

if [ "$(uname -m)" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if [ -f "$HOMEBREW_PREFIX/bin/brew" ]; then
  # Load Homebrew's variables
  eval "$("$HOMEBREW_PREFIX/bin/brew" shellenv)"
fi

## Erlang and Elixir

# https://www.erlang.org/doc/man/erlc.html
export ERLC_USE_SERVER=true

# https://erlang.mk/guide/building.html
export MAKEFLAGS="-j$(($(nproc) + 1))"

# https://hexdocs.pm/iex/IEx.html
export ERL_AFLAGS="-kernel shell_history enabled"

# https://github.com/asdf-vm/asdf-erlang/blob/master/README.md#setting-the-environment-variable-in-bash
export KERL_BUILD_DOCS="yes"

## GNU Pretty Good Privacy (PGP)

export GNUPGHOME="$XDG_DATA_HOME/gnupg"
mkdir -p "$GNUPGHOME"

# https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
chown -R "$(whoami)" "$GNUPGHOME"
chmod 700 "$GNUPGHOME"

## Other software

export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export LESSHISTFILE="-"
export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"

## Android

export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"

## PATH

# By prepending paths, the system will prioritize these directories over the
# default ones when searching for executables.
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/var/lib/flatpak/exports/bin:$PATH"
export PATH="$HOME/.local/share/flatpak/exports/bin:$PATH"
export PATH="$ANDROID_HOME/emulator:$PATH"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
export PATH="$XDG_CONFIG_HOME/flutter/bin:$PATH"
export PATH="$XDG_CONFIG_HOME/herd-lite/bin:$PATH"
export PATH="$XDG_DATA_HOME/npm/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
