#!/bin/bash

command_exists() { command -v "$1" &>/dev/null; }

## User-defined

export DOTFILES_DIR="$HOME/.dotfiles"
export VIMWIKI_DIR="$HOME/Documents/vimwiki"

export GIT_USER_NAME="Masatoshi Nishiguchi"
export GIT_USER_EMAIL="7563926+mnishiguchi@users.noreply.github.com"
export GITHUB_USER_NAME="mnishiguchi"

## Editors

command_exists vim && EDITOR="vim"
command_exists nvim && EDITOR="nvim"

# https://hexdocs.pm/iex/IEx.Helpers.html#open/1
command_exists codium && ELIXIR_EDITOR="codium --goto"
command_exists code && ELIXIR_EDITOR="code --goto"

export EDITOR="$EDITOR"
export VISUAL="$EDITOR"
export ELIXIR_EDITOR="$ELIXIR_EDITOR"

## Manual pages

export MANPAGER="less -R --use-color --color=d+r --color=u+y"

## fzf

if command_exists fzf; then
  # https://github.com/junegunn/fzf/wiki/Color-schemes#dracula
  export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--reverse
--color=dark
--color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f
--color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
'

  # Default command to use when input is tty
  # https://github.com/junegunn/fzf#environment-variables
  if command_exists rg; then
    export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
  else
    export FZF_DEFAULT_COMMAND='find . -type f ! -path "*git*"'
  fi
fi

## X11

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

## Homebrew

if [ "$(uname -m)" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if [ -f "$HOMEBREW_PREFIX/bin/brew" ]; then
  # Load Homebrew's variables
  eval "$("$HOMEBREW_PREFIX/bin/brew" shellenv)"
fi

## asdf

export ASDF_DIR="$XDG_CONFIG_HOME/asdf"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"

## Erlang and Elixir

# https://www.erlang.org/doc/man/erlc.html
export ERLC_USE_SERVER=true

# https://erlang.mk/guide/building.html
export MAKEFLAGS="-j$(($(nproc) + 1))"

# https://hexdocs.pm/iex/IEx.html
export ERL_AFLAGS="-kernel shell_history enabled"

# https://github.com/asdf-vm/asdf-erlang/blob/master/README.md#setting-the-environment-variable-in-bash
export KERL_BUILD_DOCS="yes"

## npm

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_PATH="$XDG_CONFIG_HOME/npm"
export NPM_BIN="$XDG_CONFIG_HOME/npm/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/npm"

## Other software

export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export LESSHISTFILE="-"
export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"

## PATH

# append
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/var/lib/flatpak/exports/bin"
export PATH="$PATH:$HOME/.local/share/flatpak/exports/bin"
export PATH="$PATH:$NPM_BIN"
