return {
  filetypes = {
    'blade',
    'css',
    'eelixir',
    'elixir',
    'eruby',
    'heex',
    'html',
    'javascript',
    'javascriptreact',
    'less',
    'markdown',
    'pug',
    'sass',
    'scss',
    'typescriptreact',
  },
  init_options = {
    includeLanguages = {
      html            = 'html',
      javascript      = 'javascript',
      javascriptreact = 'html',
      typescript      = 'typescript',
      typescriptreact = 'html',
      vue             = 'html',
      ruby            = 'html',
      eelixir         = 'html',
      heex            = 'html',
      markdown        = 'html',
      css             = 'css',
      scss            = 'scss',
      sass            = 'sass',
      less            = 'less',
    },
  },
}
