# https://starship.rs/config

# https://elixirforum.com/t/starship-cross-shell-prompt-error-starship-utils-executing-command-elixir-timed-out/37723/4?u=mnishiguchi
command_timeout	= 5000

[aws]
symbol = "🅰 "

[gcloud]
symbol = "🅶 "

[package]
disabled = true

[directory]
truncate_to_repo = false

[elixir]
format = 'via [$version \(OTP $otp_version\) ]($style) '

[nodejs]
format = "via [$version]($style) "

[ruby]
format = "via [$version]($style) "
