vim.keymap.set('n', '<leader>gs', ':vertical Git<CR>', { desc = ':Git' })
vim.keymap.set('n', '<leader>gd', vim.cmd.Gdiff, { desc = ':Gdiff' })
vim.keymap.set('n', '<leader>gw', vim.cmd.Gwrite, { desc = ':Gwrite' })
vim.keymap.set('n', '<leader>gr', vim.cmd.Gread, { desc = ':Gread' })
vim.keymap.set("n", "<leader>gcc", ":Git commit -v<CR>")
vim.keymap.set("n", "<leader>gca", ":Git commit -v --amend<CR>")
vim.keymap.set("n", "<leader>gf", ":Git fetch<CR>")
vim.keymap.set("n", "<leader>gp", ":Git push<CR>")
vim.keymap.set("n", "<leader>gpf", ":Git push --force-with-lease<CR>")
