#!/usr/bin/env zsh

source "$HOME/.config/shell/variables"

## ZSH-specific variables

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000
